### ISSUE TITLE
打包到了AUR上

### ISSUE THREAD

**Issue by ayalhw** [hosxy/rime-aurora-pinyin#1]
很暴力的打了个包到了AUR上（基本抄的肥猫的 PKGBUILD

地址在这里  https://aur.archlinux.org/packages/rime-aurora-pinyin/

没有事先请求，还请见谅

**Comment by hosxy** [comment]
欢迎打包😋
我也用 Arch Linux，但是我太懒了😭

**Comment by AlynxZhou** [comment]
因为这个仓库好像没有 release，上面那个没见经常更新，我打了一个 git 包：<https://aur.archlinux.org/packages/rime-aurora-pinyin-git>.

**Comment by CoelacanthusHex** [comment]
考虑到这些方案几乎没有 tag 和 release，我觉得移除普通包仅保留 -git 比较合理
