### ISSUE TITLE
单字母m和n在Rime下无法正确输出以m和n开头的字

### ISSUE THREAD

**Issue by jim-kirisame** [hosxy/rime-aurora-pinyin#3]
推测是码表内含有单字母m和n的条目的问题

**Comment by ayaka14732** [comment]
It is indeed a *feature*. Or you can change the default behaviour by adding

```
- derive/^([mn]).+$/$1/
```

to `speller:algrbra`.

**Comment by hosxy** [comment]
单声母/双声母(无韵母)的汉字的确是存在的，
同意 @ayaka14732 的方法
