### ISSUE TITLE
『求助』使用习惯词库转移

### ISSUE THREAD

**Issue by BriefHistory** [hosxy/rime-aurora-pinyin#6]
请问 如何将自己使用的别的输入方案 的词库转移到 极光？
举例： 我之前使用的自带的明月拼音简化字,然后有一些 人名的词库,现在怎么copy到这个方案？

**Comment by hosxy** [comment]
如果你是指用户词库的话有点坑，因为明月拼音简化字的用户词库是以繁体字记录的，如果你真的很需要转移的话，你需要进行简繁转换，然后使用同步进行导入导出

如果是外挂词库的话比较简单，参考
https://gist.github.com/lotem/5443073
https://github.com/rime-aca/dictionaries
